### ISSUE TITLE
How to use it to show loading screen when route changed ?

### ISSUE THREAD

**Issue by ZerosDev** [ankurk91/vue-loading-overlay#47] opened 2020-04-19 16:37 UTC
Is it possible to display the loading screen when the route changes?
What I want is, if someone switch to other route the loading screen will appear. Currently the loading screen only appears when the page has been rendered so that the application appears unresponsive when the internet connection is slow
I found it using router.beforeEach() but I don't know how to implement this package because I usually set the isLoading property in data()

**Comment by ankurk91** [comment] 2020-04-19 17:05
Duplicate of
https://github.com/ankurk91/vue-loading-overlay/issues/21

**Closed by ankurk91** 2020-04-19 17:05 UTC

**Comment by ZerosDev** [comment] 2020-04-19 17:07
Thank you
